### ISSUE TITLE
Image not displaying (random characters).

### ISSUE THREAD

**Issue by mathieuboudreau** [MRtrix3/mrpeek#13]
I followed all your instructions to the best of my ability (installed from source, etc). Using MacOS.

The final call of `mrpeek` with a given NIFTI  just gives me the following screen:
<img width="883" alt="Capture d’écran 2020-06-18 à 18 34 51" src="https://user-images.githubusercontent.com/1421029/85071706-7b49d800-b192-11ea-9846-49b26b7073e2.png">

**Comment by dchristiaens** [comment]
The default terminal on macOS does not support the sixel format used to render the image inline, so what you're seeing there is the raw sixel encoding of the current frame. 

On macOS, you need to use [iTerm2](https://www.iterm2.com) instead.

**Comment by mathieuboudreau** [comment]
Woops - my bad! That resolves it, thanks!

<img width="910" alt="Capture d’écran 2020-06-18 à 18 43 12" src="https://user-images.githubusercontent.com/1421029/85072364-9537ea80-b193-11ea-865c-9c7d99ba39fb.png">

**Comment by dchristiaens** [comment]
Sorry about that. This has all been written as a hackathon project in the last 3 days, so documentation is clearly lacking. We are a bit overwhelmed by the amount of interest this has generated. I've updated the README to hopefully clarify this.

**Comment by mathieuboudreau** [comment]
Haha no worries - I'm at the OHBM hackathon too =)
