### ISSUE TITLE
Feature request: orthoview mode

### ISSUE THREAD

**Issue by jdtournier** [MRtrix3/mrpeek#17]
Would be good to add support for the 3 views in a row type display, as per `mrview` in ortho mode with 'display in a row' enabled:

![Screenshot from 2020-06-19 12-51-43](https://user-images.githubusercontent.com/3221000/85130008-06c37780-b22c-11ea-9601-fbf98a3e9b2d.png)

**Comment by dchristiaens** [comment]
in progress on [orthoview](/MRtrix3/mrpeek/tree/orthoview).

**Comment by dchristiaens** [comment]
Closing this. Continue discussion in #28.
