### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by clemjeancmj** [MRtrix3/mrpeek#45]
Hi everyone,

Sorry but I need some help to install mrpeek.
I just downloaded iterm2 and tried to install mrpeek but at the building step something went wong with the following error : 

(base) clementjean@MacBook-Pro mrpeek % ../mrtrix3/build

ERROR: cannot find header file "colourmap.h" (from file "src/sixel.h")
(base) clementjean@MacBook-Pro mrpeek %

I don't now if he problem come from my mrtrix or my mrpeek installation.

Hope you could help me with this 

Best Regards

**Comment by jdtournier** [comment]
That's odd, the file it's looking for is part of the standard MRtrix base ([found here](https://github.com/MRtrix3/mrtrix3/blob/master/src/colourmap.h)). Is the MRtrix repo you're building against up to date? Are you using the latest version of the `master` branch?

**Comment by clemjeancmj** [comment]
Thank you for your help !
I just tried with the other sixel.h file and there are other errors :

(base) clementjean@MacBook-Pro Desktop % cd /Users/clementjean/mrpeek
(base) clementjean@MacBook-Pro mrpeek % ../mrtrix3/build
(2/5) [CC] tmp/src/sixel.o
(1/5) [CC] tmp/src/project_version.o
(3/5) [CC] tmp/cmd/mrpeek.o
(4/5) [LD] ../mrtrix3/lib/libmrtrix.dylib
ERROR: (2/5) [CC] tmp/src/sixel.o
ERROR: (3/5) [CC] tmp/cmd/mrpeek.o

ERROR: (2/5) [CC] tmp/src/sixel.o

clang++ -c -std=c++11 -DMRTRIX_BUILD_TYPE="release version" -DMRTRIX_MACOSX -fPIC -mmacosx-version-min=10.15 -DMRTRIX_WORD64 -DMRTRIX_TIFF_SUPPORT -idirafter /usr/local/Cellar/libtiff/4.1.0/include -DEIGEN_FFTW_DEFAULT -idirafter /usr/local/Cellar/fftw/3.3.8_1/include -Wall -O3 -DNDEBUG -DMRTRIX_PROJECT -Isrc -I../mrtrix3/src -I../mrtrix3/core -Icmd -idirafter /usr/local/Cellar/eigen/3.3.7/include/eigen3 -DEIGEN_DONT_PARALLELIZE src/sixel.cpp -o tmp/src/sixel.o

failed with output

src/sixel.cpp:10:17: error: use of undeclared identifier 'CMap'
    std::string CMap::specifier () const {
                ^
src/sixel.cpp:30:17: error: use of undeclared identifier 'Encoder'
    std::string Encoder::write () {
                ^
src/sixel.cpp:50:17: error: use of undeclared identifier 'Encoder'
    std::string Encoder::encode (int y0) {
                ^
src/sixel.cpp:73:17: error: use of undeclared identifier 'Encoder'
    std::string Encoder::encode (const int y0, const int intensity)
                ^
src/sixel.cpp:105:20: error: use of undeclared identifier 'VT'
      std::cout << VT::CursorHome << SixelStart << "#0;2;0;0;0$#0?!200-" << Sixe
lStop;
                   ^
src/sixel.cpp:105:38: error: use of undeclared identifier 'SixelStart'
      std::cout << VT::CursorHome << SixelStart << "#0;2;0;0;0$#0?!200-" << Sixe
lStop;
                                     ^
src/sixel.cpp:105:77: error: use of undeclared identifier 'SixelStop'
      std::cout << VT::CursorHome << SixelStart << "#0;2;0;0;0$#0?!200-" << Sixe
lStop;
                                                                            ^
src/sixel.cpp:107:32: error: use of undeclared identifier 'VT'
      struct CallBack : public VT::EventLoop::CallBack
                               ^
src/sixel.cpp:107:47: error: expected class name
      struct CallBack : public VT::EventLoop::CallBack
                                              ^
src/sixel.cpp:110:68: error: only virtual member functions can be marked 'overri
de'
        bool operator() (int event, const std::vector<int>& param) override {
                                                                   ^~~~~~~~~
src/sixel.cpp:112:26: error: use of undeclared identifier 'VT'
            std::cout << VT::RequestCursorPosition;
                         ^
src/sixel.cpp:116:25: error: use of undeclared identifier 'VT'
          if (event == (VT::CSImask | 'R')) {
                        ^
src/sixel.cpp:127:7: error: use of undeclared identifier 'VT'
      VT::EventLoop (callback).run();
      ^
13 errors generated.

ERROR: (3/5) [CC] tmp/cmd/mrpeek.o

clang++ -c -std=c++11 -DMRTRIX_BUILD_TYPE="release version" -DMRTRIX_MACOSX -fPI
C -mmacosx-version-min=10.15 -DMRTRIX_WORD64 -DMRTRIX_TIFF_SUPPORT -idirafter /u
sr/local/Cellar/libtiff/4.1.0/include -DEIGEN_FFTW_DEFAULT -idirafter /usr/local
/Cellar/fftw/3.3.8_1/include -Wall -O3 -DNDEBUG -DMRTRIX_PROJECT -Isrc -I../mrtr
ix3/src -I../mrtrix3/core -Icmd -idirafter /usr/local/Cellar/eigen/3.3.7/include
/eigen3 -DEIGEN_DONT_PARALLELIZE cmd/mrpeek.cpp -o tmp/cmd/mrpeek.o

failed with output

In file included from cmd/mrpeek.cpp:3:
In file included from ../mrtrix3/core/image.h:27:
../mrtrix3/core/formats/mrtrix_utils.h:176:27: warning: loop variable 'line' of
type 'const std::__1::basic_string<char>' creates a copy from type 'const std::_
_1::basic_string<char>' [-Wrange-loop-analysis]
          for (const auto line : split_lines (i.second))
                          ^
../mrtrix3/core/formats/mrtrix_utils.h:176:16: note: use reference type 'const s
td::__1::basic_string<char> &' to prevent copying
          for (const auto line : split_lines (i.second))
               ^~~~~~~~~~~~~~~~~
                          &
../mrtrix3/core/formats/mrtrix_utils.h:175:25: warning: loop variable 'i' of typ
e 'const std::__1::pair<const std::__1::basic_string<char>, std::__1::basic_stri
ng<char> >' creates a copy from type 'const std::__1::pair<const std::__1::basic
_string<char>, std::__1::basic_string<char> >' [-Wrange-loop-analysis]
        for (const auto i : H.keyval())
                        ^
../mrtrix3/core/formats/mrtrix_utils.h:175:14: note: use reference type 'const s
td::__1::pair<const std::__1::basic_string<char>, std::__1::basic_string<char> >
 &' to prevent copying
        for (const auto i : H.keyval())
             ^~~~~~~~~~~~~~
                        &
cmd/mrpeek.cpp:14:17: error: expected namespace name
using namespace VT;
                ^
cmd/mrpeek.cpp:150:1: error: use of undeclared identifier 'Sixel'
Sixel::ColourMaps colourmaps;
^
cmd/mrpeek.cpp:151:1: error: use of undeclared identifier 'Sixel'
Sixel::ColourMaps plot_cmaps;
^
cmd/mrpeek.cpp:156:25: error: use of undeclared identifier 'Down'
    return move_cursor (Down, n);
                        ^
cmd/mrpeek.cpp:212:21: error: use of undeclared identifier 'ClearLine'
  std::string out = ClearLine;
                    ^
cmd/mrpeek.cpp:218:28: error: use of undeclared identifier 'LeftRightArrow'
        out += std::string(LeftRightArrow) + TextForegroundYellow;
                           ^
cmd/mrpeek.cpp:218:46: error: use of undeclared identifier 'TextForegroundYellow
'
        out += std::string(LeftRightArrow) + TextForegroundYellow;
                                             ^
cmd/mrpeek.cpp:219:14: error: use of undeclared identifier 'TextUnderscore'
      out += TextUnderscore;
             ^
cmd/mrpeek.cpp:223:28: error: use of undeclared identifier 'UpDownArrow'
        out += std::string(UpDownArrow) + TextForegroundYellow;
                           ^
cmd/mrpeek.cpp:223:43: error: use of undeclared identifier 'TextForegroundYellow
'
        out += std::string(UpDownArrow) + TextForegroundYellow;
                                          ^
cmd/mrpeek.cpp:224:14: error: use of undeclared identifier 'TextUnderscore'
      out += TextUnderscore;
             ^
cmd/mrpeek.cpp:228:28: error: use of undeclared identifier 'LeftRightArrow'
        out += std::string(LeftRightArrow) + TextForegroundYellow;
                           ^
cmd/mrpeek.cpp:228:46: error: use of undeclared identifier 'TextForegroundYellow
'
        out += std::string(LeftRightArrow) + TextForegroundYellow;
                                             ^
cmd/mrpeek.cpp:230:28: error: use of undeclared identifier 'TextReset'
    out += str(focus[d]) + TextReset + " ";
                           ^
cmd/mrpeek.cpp:234:26: error: use of undeclared identifier 'UpDownArrow'
      out += std::string(UpDownArrow) + TextForegroundYellow;
                         ^
cmd/mrpeek.cpp:234:41: error: use of undeclared identifier 'TextForegroundYellow
'
      out += std::string(UpDownArrow) + TextForegroundYellow;
                                        ^
cmd/mrpeek.cpp:235:34: error: use of undeclared identifier 'TextReset'
    out += str(image.index(n)) + TextReset + " ";
                                 ^
cmd/mrpeek.cpp:272:35: error: use of undeclared identifier 'Sixel'
void autoscale (ImageType& image, Sixel::CMap& cmap)
                                  ^
cmd/mrpeek.cpp:300:24: error: use of undeclared identifier 'Sixel'
void draw_frame (const Sixel::ViewPort& view, int index)
                       ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
2 warnings and 20 errors generated.
(END)

I don't know if mrtrix repo is up to date, I downloaded it last year.
Do you think I should uninstall and install mrtrix again ?

Thank you

**Comment by jdtournier** [comment]
Ok, I'm really confused now... What do you mean by "the other sixel.h file"? It looks like it's missing the `#include "colourmap.h"` line or something...

I think the best thing to do is for you to describe with full commands every step you've taken to get to this stage, right from downloading or cloning both the mrpeek and MRtrix repos. It sounds like something might have gone wrong somewhere upstream, as the errors you're showing shouldn't happen if everything was set to correctly..

**Comment by clemjeancmj** [comment]
Thank you so much for your time, There was no colormap. cpp ans colormap.h in my mrtrix src, the issue came from there.
I am to blame for the errors in my previous message, I tried to copy the colormap.h from mrtrix repo into the mrpeek one.
It works perfectly right now and will really help me :)
![image](https://user-images.githubusercontent.com/64259143/108633811-9cc43780-7476-11eb-9a07-f0d7ce6de762.png)

thank you for everything
